version: '3.9'
services:
  app:
    image: app
    container_name: app
    environment:
      DATABASE_URL: 'postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}'
      GOOGLE_ID: ${GOOGLE_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
      AUTH_URL: ${AUTH_URL}
      AUTH_SECRET: ${AUTH_SECRET}
      EMAIL_SERVER_USER: ${EMAIL_SERVER_USER}
      EMAIL_SERVER_PASSWORD: ${EMAIL_SERVER_PASSWORD}
      EMAIL_SERVER_HOST: ${EMAIL_SERVER_HOST}
      EMAIL_SERVER_PORT: ${EMAIL_SERVER_PORT}
      EMAIL_FROM: ${EMAIL_FROM}
      NEXT_TELEMETRY_DISABLED: 1
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:14.8-alpine3.18
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - db-data:/var/lib/postgresql/data
      # \\wsl$\docker-desktop-data\data\docker\volumes
    ports:
      - '5432:5432'

volumes:
  db-data:
