version: '3.9'
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.5-alpine
    container_name: nginx-proxy
    ports:
      - '80:80'
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
  app:
    image: app:release
    container_name: app
    environment:
      DATABASE_URL: 'postgresql://${DATABASE_USER}:${DATABASE_PASSWORD}@db:5432/${DATABASE_NAME}'
      NEXT_TELEMETRY_DISABLED: 1
      VIRTUAL_HOST: app.local
      VIRTUAL_PORT: 3000
    expose:
      - '3000'
    env_file:
      - .env
    build: .
    # ports:
    #   - '3000:3000'
    depends_on:
      - db
  db:
    image: postgres:14.8-alpine3.18
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - db-data:/var/lib/postgresql/data
      # \\wsl$\docker-desktop-data\data\docker\volumes
    expose:
      - '5432'
    # ports:
    #   - '5432:5432'

volumes:
  db-data:
