version: '3.9'
services:
  app:
    image: app
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - db
    networks:
      - proxy
      - internal
  db:
    image: postgres:14.8-alpine3.18
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: '/var/lib/postgresql/data/pgdata'
    volumes:
      - db-data:/var/lib/postgresql/data
      # \\wsl$\docker-desktop-data\data\docker\volumes
    ports:
      - '5432:5432'
    networks:
      - proxy
      - internal

volumes:
  db-data:

networks:
  proxy:
    external: true
  internal:
    external: false
